### ISSUE TITLE
SQLite3 giving error on 'relationships' database

### ISSUE THREAD

**Issue by bwolatz** [bwolatz/CSCI4900#37]
If you look in the schema you can see a very handy schema for "Relationships". I went ahead and tryied to use it, but it says that the table is encrypted. Take a look for yourself. No idea how to solve this one.

Here is copy and paste error text

Traceback (most recent call last):
  File "/usr/share/fossology/nomos/agent/venv/bin/dosocs2", line 9, in <module>
    load_entry_point('dosocs2==0.16.1', 'console_scripts', 'dosocs2')()
  File "/usr/share/fossology/nomos/agent/venv/local/lib/python2.7/site-packages/dosocs2-0.16.1-py2.7.egg/dosocs2/dosocs2.py", line 363, in main
    printval = spdxdb.create_relation(conn, **kwargs)
  File "/usr/share/fossology/nomos/agent/venv/local/lib/python2.7/site-packages/dosocs2-0.16.1-py2.7.egg/dosocs2/spdxdb.py", line 167, in create_relation
    insert(conn, db.relationships, rel_params)
  File "/usr/share/fossology/nomos/agent/venv/local/lib/python2.7/site-packages/dosocs2-0.16.1-py2.7.egg/dosocs2/spdxdb.py", line 31, in insert
    result = conn.execute(query)
  File "/usr/share/fossology/nomos/agent/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/share/fossology/nomos/agent/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/share/fossology/nomos/agent/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/share/fossology/nomos/agent/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/share/fossology/nomos/agent/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/share/fossology/nomos/agent/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/share/fossology/nomos/agent/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/share/fossology/nomos/agent/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'INSERT INTO relationships (left_identifier_id, right_identifier_id, relationship_type_id, relationship_comment) VALUES (?, ?, ?, ?)'] [parameters: (1, 1, 1, 'DEPENDENCY_OF')]

**Comment by bwolatz** [comment]
solved by nikhit
